### ISSUE TITLE
I get Forbidden 

### ISSUE THREAD

**Issue by wesbos** [letz/fake-email#1]
If I click a link or run this JS code I get Forbidden. It seems it only works when you visit the page directly and not from another source. 

Any idea?

``` js
fetch('https://fake-emails.herokuapp.com/check?email=wesbos@gmail.com').then(data => data.json()).then(res => { console.log(res) })
```

**Comment by letz** [comment]
Its a CORS issue, I gonna fix it

**Comment by letz** [comment]
Fixed: https://github.com/letz/fake-email/commit/ced75946a4da37b3ef6c39a54eb97a73ae255de2
